package mod.cockroach.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ModAnimationDefinitions {

        public static final AnimationDefinition COCKROACH_FLY = AnimationDefinition.Builder.withLength(1.625f).looping()
                        .addAnimation("Head",
                                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.5f, 0.5f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Head",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("InsideWings",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.041676664f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.08343333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.125f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.16766666f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.20834334f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.2916767f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.3433333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.375f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.4167667f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.4583433f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5416766f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5834334f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.625f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.6766666f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.7083434f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.7916766f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.8343334f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.875f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.9167666f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.9583434f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.0416767f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.0834333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.125f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.1676667f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.2083433f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.2916767f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.3433333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.375f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.4167667f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.4583433f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.5416767f,
                                                                        KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("OverlapWings",
                                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 1.5f, 1.8f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("OverlapWings",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Cockroach",
                                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, 3f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Cockroach",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("OverlapTwo",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 12.5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("OverlapOne",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -12.5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .build();
        public static final AnimationDefinition COCKROACH_WALKING = AnimationDefinition.Builder.withLength(1f).looping()
                        .addAnimation("Leg1",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg2",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg3",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg4",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg5",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg6",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .build();
        public static final AnimationDefinition COCKROACH_CLIMBING = AnimationDefinition.Builder.withLength(1f)
                        .looping()
                        .addAnimation("Leg1",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg2",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg3",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg4",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg5",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Leg6",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Cockroach",
                                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 5.5f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Cockroach",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.LINEAR)))
                        .build();
}
